### ISSUE TITLE
Container with SSL cannot start after being shut down

### ISSUE THREAD

**Issue by stellirin** [ibm-messaging/mq-container#71]
I enabled SSL on my MQ container. On first start everything works as expected. However when starting the container a second time after it was shut down, the container cannot start.

docker-compose.yml:
```
version: '3.5'

services:
  mq:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      abc:
        aliases:
          - mq
    ports:
      - "1414:1414"
      - "9443:9443"

networks:
  abc:
```

Dockerfile:
```
FROM store/ibmcorp/mqadvanced-server-dev:9.0.5.0

ENV LICENSE=accept \
    MQ_DEV=false \
    MQ_QMGR_NAME=ABC \
    MQ_ADMIN_PASSWORD=testABC123 \
    MQ_APP_PASSWORD=testABC123 \
    MQ_TLS_KEYSTORE=/opt/abc/ibmq.keystore.p12 \
    MQ_TLS_PASSPHRASE=testABC123

COPY ibmq.keystore.p12 /opt/abc/ibmq.keystore.p12
COPY mq/99-queues.mqsc /etc/mqm/
```

99-queues.mqsc:
```
STOP LISTENER('SYSTEM.LISTENER.TCP.1')

* ABC queues
DEFINE QLOCAL('ABC.HELLO.WORLD') REPLACE

* Use a different dead letter queue, for undeliverable messages
DEFINE QLOCAL('ABC.DEAD.LETTER.QUEUE') REPLACE
ALTER QMGR DEADQ('ABC.DEAD.LETTER.QUEUE')

* ABC topics
DEFINE TOPIC('ABC.BASE.TOPIC') TOPICSTR('abc/') REPLACE

* ABC channels (Application + Admin)
DEFINE CHANNEL('ABC.ADMIN.SVRCONN') CHLTYPE(SVRCONN) REPLACE
DEFINE CHANNEL('ABC.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('app') REPLACE

* ABC connection authentication
DEFINE AUTHINFO('ABC.AUTHINFO') AUTHTYPE(IDPWOS) CHCKCLNT(REQDADM) CHCKLOCL(OPTIONAL) ADOPTCTX(YES) REPLACE
ALTER QMGR CONNAUTH('ABC.AUTHINFO')
ALTER QMGR CERTLABL('ibmq')
ALTER CHANNEL('ABC.ADMIN.SVRCONN') CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_256_GCM_SHA384) SSLCAUTH(OPTIONAL)
ALTER CHANNEL('ABC.APP.SVRCONN') CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_256_GCM_SHA384) SSLCAUTH(OPTIONAL)
REFRESH SECURITY(*) TYPE(CONNAUTH)

* ABC channel authentication rules
SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('Back-stop rule - Blocks everyone') ACTION(REPLACE)
SET CHLAUTH('ABC.APP.SVRCONN') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED) DESCR('Allows connection via APP channel') ACTION(REPLACE)
SET CHLAUTH('ABC.ADMIN.SVRCONN') TYPE(BLOCKUSER) USERLIST('nobody') DESCR('Allows admins on ADMIN channel') ACTION(REPLACE)
SET CHLAUTH('ABC.ADMIN.SVRCONN') TYPE(USERMAP) CLNTUSER('admin') USERSRC(CHANNEL) DESCR('Allows admin user to connect via ADMIN channel') ACTION(REPLACE)

* ABC authority records
SET AUTHREC GROUP('mqclient') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ,SETALL)
SET AUTHREC PROFILE('ABC.**') GROUP('mqclient') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT,SETALL)
SET AUTHREC PROFILE('ABC.**') GROUP('mqclient') OBJTYPE(TOPIC) AUTHADD(PUB,SUB)

* ABC listener
DEFINE LISTENER('ABC.LISTENER.TCP') TRPTYPE(TCP) PORT(1414) CONTROL(QMGR) REPLACE
START LISTENER('ABC.LISTENER.TCP')
```

First start:
```
docker-compose up mq
Creating abc_mq_1 ... done
Attaching to abc_mq_1
mq_1       | 2018-04-28T05:36:41.119Z Set password for "admin" user
mq_1       | 2018-04-28T05:36:41.132Z Set password for "app" user
mq_1       | 2018-04-28T05:36:45.919Z Using queue manager name: ABC
mq_1       | 2018-04-28T05:36:45.919Z CPU architecture: amd64
mq_1       | 2018-04-28T05:36:45.919Z Linux kernel version: 4.9.87-linuxkit-aufs
mq_1       | 2018-04-28T05:36:45.919Z Base image detected: Ubuntu 16.04.4 LTS
mq_1       | 2018-04-28T05:36:45.919Z Maximum file handles: 524288
mq_1       | 2018-04-28T05:36:45.919Z Running as user ID 0 (root) with primary group 0
mq_1       | 2018-04-28T05:36:45.919Z Detected capabilities: AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT
mq_1       | 2018-04-28T05:36:45.919Z No volume detected. Persistent messages may be lost
mq_1       | 2018-04-28T05:36:45.927Z Created directory structure under /var/mqm
mq_1       | 2018-04-28T05:36:45.927Z Creating queue manager ABC
mq_1       | 2018-04-28T05:36:45.929Z Starting web server
mq_1       | 2018-04-28T05:36:48.076Z Starting queue manager
mq_1       | 2018-04-28T05:36:46.115Z AMQ6287I: IBM MQ V9.0.5.0 (p905-L180306.DE).
mq_1       | 2018-04-28T05:36:46.115Z AMQ5051I: The queue manager task 'LOGGER-IO' has started.
mq_1       | 2018-04-28T05:36:46.147Z AMQ5041I: The queue manager task 'LOGGER-IO' has ended.
mq_1       | 2018-04-28T05:36:46.218Z AMQ5051I: The queue manager task 'LOGGER-IO' has started.
mq_1       | 2018-04-28T05:36:46.224Z AMQ7229I: 4 log records accessed on queue manager 'ABC' during the log replay phase.
mq_1       | 2018-04-28T05:36:46.224Z AMQ7230I: Log replay for queue manager 'ABC' complete.
mq_1       | 2018-04-28T05:36:46.227Z AMQ7231I: 0 log records accessed on queue manager 'ABC' during the recovery phase.
mq_1       | 2018-04-28T05:36:46.228Z AMQ7232I: Transaction manager state recovered for queue manager 'ABC'.
mq_1       | 2018-04-28T05:36:46.239Z AMQ7233I: 0 out of 0 in-flight transactions resolved for queue manager 'ABC'.
mq_1       | 2018-04-28T05:36:46.239Z AMQ5051I: The queue manager task 'CHECKPOINT' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.250Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.250Z AMQ5037I: The queue manager task 'ERROR-LOG' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:46.249Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:47.983Z AMQ8048I: Default objects statistics : 85 created. 0 replaced. 0 failed.
mq_1       | 2018-04-28T05:36:47.986Z AMQ8003I: IBM MQ queue manager 'ABC' started using V9.0.5.0.
mq_1       | 2018-04-28T05:36:47.997Z AMQ5041I: The queue manager task 'APP-SIGNAL' has ended.
mq_1       | 2018-04-28T05:36:47.997Z AMQ5041I: The queue manager task 'APP-SIGNAL' has ended.
mq_1       | 2018-04-28T05:36:48.000Z AMQ5041I: The queue manager task 'ERROR-LOG' has ended.
mq_1       | 2018-04-28T05:36:48.028Z AMQ5041I: The queue manager task 'CHECKPOINT' has ended.
mq_1       | 2018-04-28T05:36:48.045Z AMQ5041I: The queue manager task 'LOGGER-IO' has ended.
mq_1       | 2018-04-28T05:36:48.051Z AMQ8004I: IBM MQ queue manager 'ABC' ended.
mq_1       | 2018-04-28T05:36:48.325Z Started queue manager
mq_1       | 2018-04-28T05:36:48.374Z Output for "runmqsc" with /etc/mqm/20-dev-tls.mqsc:
mq_1       |    5724-H72 (C) Copyright IBM Corp. 1994, 2018.
mq_1       |    Starting MQSC for queue manager ABC.
mq_1       |
mq_1       |
mq_1       |         1 : ALTER QMGR SSLKEYR('/run/runmqdevserver/tls/key')
mq_1       |    AMQ8005I: IBM MQ queue manager changed.
mq_1       |         2 : ALTER QMGR CERTLABL('devcert')
mq_1       |    AMQ8005I: IBM MQ queue manager changed.
mq_1       |    2 MQSC commands read.
mq_1       |    No commands have a syntax error.
mq_1       |    All valid MQSC commands were processed.
mq_1       |
mq_1       | 2018-04-28T05:36:48.190Z AMQ5051I: The queue manager task 'LOGGER-IO' has started.
mq_1       | 2018-04-28T05:36:48.200Z AMQ7229I: 5 log records accessed on queue manager 'ABC' during the log replay phase.
mq_1       | 2018-04-28T05:36:48.201Z AMQ7230I: Log replay for queue manager 'ABC' complete.
mq_1       | 2018-04-28T05:36:48.205Z AMQ7231I: 0 log records accessed on queue manager 'ABC' during the recovery phase.
mq_1       | 2018-04-28T05:36:48.205Z AMQ7232I: Transaction manager state recovered for queue manager 'ABC'.
mq_1       | 2018-04-28T05:36:48.222Z AMQ7233I: 0 out of 0 in-flight transactions resolved for queue manager 'ABC'.
mq_1       | 2018-04-28T05:36:48.226Z AMQ5051I: The queue manager task 'CHECKPOINT' has started.
mq_1       | 2018-04-28T05:36:48.237Z AMQ5037I: The queue manager task 'ERROR-LOG' has started.
mq_1       | 2018-04-28T05:36:48.237Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.237Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.237Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.241Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.237Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.237Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.241Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.244Z AMQ5037I: The queue manager task 'APP-SIGNAL' has started.
mq_1       | 2018-04-28T05:36:48.261Z AMQ8003I: IBM MQ queue manager 'ABC' started using V9.0.5.0.
mq_1       | 2018-04-28T05:36:48.262Z AMQ5037I: The queue manager task 'DEFERRED_DELIVERY' has started.
mq_1       | 2018-04-28T05:36:48.273Z AMQ9410I: Repository manager started.
mq_1       | 2018-04-28T05:36:48.273Z AMQ5051I: The queue manager task 'ACTVTRC' has started.
mq_1       | 2018-04-28T05:36:48.273Z AMQ5051I: The queue manager task 'ASYNCQ' has started.
mq_1       | 2018-04-28T05:36:48.273Z AMQ5051I: The queue manager task 'EXPIRER' has started.
mq_1       | 2018-04-28T05:36:48.274Z AMQ5051I: The queue manager task 'DUR-SUBS-MGR' has started.
mq_1       | 2018-04-28T05:36:48.274Z AMQ5037I: The queue manager task 'DEFERRED-MSG' has started.
mq_1       | 2018-04-28T05:36:48.275Z AMQ5037I: The queue manager task 'STATISTICS' has started.
mq_1       | 2018-04-28T05:36:48.288Z AMQ5037I: The queue manager task 'MARKINTSCAN' has started.
mq_1       | 2018-04-28T05:36:48.288Z AMQ5052I: The queue manager task 'QPUBSUB-CTRLR' has started.
mq_1       | 2018-04-28T05:36:48.290Z AMQ5052I: The queue manager task 'QPUBSUB-QUEUE-NLCACHE' has started.
mq_1       | 2018-04-28T05:36:48.291Z AMQ5052I: The queue manager task 'QPUBSUB-SUBPT-NLCACHE' has started.
mq_1       | 2018-04-28T05:36:48.292Z AMQ5052I: The queue manager task 'PUBSUB-DAEMON' has started.
mq_1       | 2018-04-28T05:36:48.293Z AMQ5975I: 'IBM MQ Distributed Pub/Sub Controller' has started.
mq_1       | 2018-04-28T05:36:48.295Z AMQ5051I: The queue manager task 'TOPIC-TREE' has started.
mq_1       | 2018-04-28T05:36:48.295Z AMQ5051I: The queue manager task 'RESOURCE_MONITOR' has started.
mq_1       | 2018-04-28T05:36:48.302Z AMQ5051I: The queue manager task 'PRESERVED-Q' has started.
mq_1       | 2018-04-28T05:36:48.302Z AMQ5051I: The queue manager task 'Q-DELETION' has started.
mq_1       | 2018-04-28T05:36:48.303Z AMQ5051I: The queue manager task 'MULTICAST' has started.
mq_1       | 2018-04-28T05:36:48.304Z AMQ5975I: 'IBM MQ Distributed Pub/Sub Fan Out Task' has started.
mq_1       | 2018-04-28T05:36:48.305Z AMQ5975I: 'IBM MQ Distributed Pub/Sub Command Task' has started.
mq_1       | 2018-04-28T05:36:48.307Z AMQ5975I: 'IBM MQ Distributed Pub/Sub Publish Task' has started.
mq_1       | 2018-04-28T05:36:48.310Z AMQ5022I: The channel initiator has started. ProcessId(529).
mq_1       | 2018-04-28T05:36:48.312Z AMQ5024I: The command server has started. ProcessId(530).
mq_1       | 2018-04-28T05:36:48.314Z AMQ5026I: The listener 'SYSTEM.LISTENER.TCP.1' has started. ProcessId(531).
mq_1       | 2018-04-28T05:36:48.362Z AMQ8024I: IBM MQ channel initiator started.
mq_1       | 2018-04-28T05:36:48.384Z AMQ5806I: Queued Publish/Subscribe Daemon started for queue manager ABC.
mq_1       | 2018-04-28T05:36:48.421Z AMQ5027I: The listener 'SYSTEM.LISTENER.TCP.1' has ended. ProcessId(531).
mq_1       | 2018-04-28T05:36:48.636Z Output for "runmqsc" with /etc/mqm/99-queues.mqsc:
mq_1       |    5724-H72 (C) Copyright IBM Corp. 1994, 2018.
mq_1       |    Starting MQSC for queue manager ABC.
mq_1       |
mq_1       |
mq_1       |         1 : STOP LISTENER('SYSTEM.LISTENER.TCP.1')
mq_1       |    AMQ8706I: Request to stop IBM MQ Listener accepted.
mq_1       |           :
mq_1       |           : * Our queues
mq_1       |         2 : DEFINE QLOCAL('ABC.HELLO.WORLD') REPLACE
mq_1       |    AMQ8006I: IBM MQ queue created.
mq_1       |           :
mq_1       |           : * Use a different dead letter queue, for undeliverable messages
mq_1       |         3 : DEFINE QLOCAL('ABC.DEAD.LETTER.QUEUE') REPLACE
mq_1       |    AMQ8006I: IBM MQ queue created.
mq_1       |         4 : ALTER QMGR DEADQ('ABC.DEAD.LETTER.QUEUE')
mq_1       |    AMQ8005I: IBM MQ queue manager changed.
mq_1       |           :
mq_1       |           : * ABC topics
mq_1       |         5 : DEFINE TOPIC('ABC.BASE.TOPIC') TOPICSTR('abc/') REPLACE
mq_1       |    AMQ8690I: IBM MQ topic created.
mq_1       |           :
mq_1       |           : * ABC channels (Application + Admin)
mq_1       |         6 : DEFINE CHANNEL('ABC.ADMIN.SVRCONN') CHLTYPE(SVRCONN) REPLACE
mq_1       |    AMQ8014I: IBM MQ channel created.
mq_1       |         7 : DEFINE CHANNEL('ABC.APP.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('app') REPLACE
mq_1       |    AMQ8014I: IBM MQ channel created.
mq_1       |           :
mq_1       |           : * ABC connection authentication
mq_1       |         8 : DEFINE AUTHINFO('ABC.AUTHINFO') AUTHTYPE(IDPWOS) CHCKCLNT(REQDADM) CHCKLOCL(OPTIONAL) ADOPTCTX(YES) REPLACE
mq_1       |    AMQ8563I: IBM MQ authentication information object created.
mq_1       |         9 : ALTER QMGR CONNAUTH('ABC.AUTHINFO')
mq_1       |    AMQ8005I: IBM MQ queue manager changed.
mq_1       |        10 : ALTER QMGR CERTLABL('ibmq')
mq_1       |    AMQ8005I: IBM MQ queue manager changed.
mq_1       |        11 : ALTER CHANNEL('ABC.ADMIN.SVRCONN') CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_256_GCM_SHA384) SSLCAUTH(OPTIONAL)
mq_1       |    AMQ8016I: IBM MQ channel changed.
mq_1       |        12 : ALTER CHANNEL('ABC.APP.SVRCONN') CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_256_GCM_SHA384) SSLCAUTH(OPTIONAL)
mq_1       |    AMQ8016I: IBM MQ channel changed.
mq_1       |        13 : REFRESH SECURITY(*) TYPE(CONNAUTH)
mq_1       |    AMQ8560I: IBM MQ security cache refreshed.
mq_1       |           :
mq_1       |           : * ABC channel authentication rules
mq_1       |        14 : SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('Back-stop rule - Blocks everyone') ACTION(REPLACE)
mq_1       |    AMQ8877I: IBM MQ channel authentication record set.
mq_1       |        15 : SET CHLAUTH('ABC.APP.SVRCONN') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED) DESCR('Allows connection via APP channel') ACTION(REPLACE)
mq_1       |    AMQ8877I: IBM MQ channel authentication record set.
mq_1       |        16 : SET CHLAUTH('ABC.ADMIN.SVRCONN') TYPE(BLOCKUSER) USERLIST('nobody') DESCR('Allows admins on ADMIN channel') ACTION(REPLACE)
mq_1       |    AMQ8877I: IBM MQ channel authentication record set.
mq_1       |        17 : SET CHLAUTH('ABC.ADMIN.SVRCONN') TYPE(USERMAP) CLNTUSER('admin') USERSRC(CHANNEL) DESCR('Allows admin user to connect via ADMIN channel') ACTION(REPLACE)
mq_1       |    AMQ8877I: IBM MQ channel authentication record set.
mq_1       |           :
mq_1       |           : * ABC authority records
mq_1       |        18 : SET AUTHREC GROUP('mqclient') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ,SETALL)
mq_1       |    AMQ8862I: IBM MQ authority record set.
mq_1       |        19 : SET AUTHREC PROFILE('ABC.**') GROUP('mqclient') OBJTYPE(QUEUE) AUTHADD(BROWSE,GET,INQ,PUT,SETALL)
mq_1       |    AMQ8862I: IBM MQ authority record set.
mq_1       |        20 : SET AUTHREC PROFILE('ABC.**') GROUP('mqclient') OBJTYPE(TOPIC) AUTHADD(PUB,SUB)
mq_1       |    AMQ8862I: IBM MQ authority record set.
mq_1       |           :
mq_1       |           : * ABC listener
mq_1       |        21 : DEFINE LISTENER('ABC.LISTENER.TCP') TRPTYPE(TCP) PORT(1414) CONTROL(QMGR) REPLACE
mq_1       |    AMQ8626I: IBM MQ listener created.
mq_1       |        22 : START LISTENER('ABC.LISTENER.TCP')
mq_1       |    AMQ8021I: Request to start IBM MQ listener accepted.
mq_1       |    22 MQSC commands read.
mq_1       |    No commands have a syntax error.
mq_1       |    All valid MQSC commands were processed.
mq_1       |
mq_1       | 2018-04-28T05:36:48.633Z AMQ5026I: The listener 'ABC.LISTENER.TCP' has started. ProcessId(580).
mq_1       | 2018-04-28T05:36:56.723Z Started web server
```

Second start:
```
docker-compose up mq
Starting abc_mq_1 ... done
Attaching to abc_mq_1
mq_1       | 2018-04-28T05:38:25.052Z Set password for "admin" user
mq_1       | 2018-04-28T05:38:25.064Z Set password for "app" user
mq_1       | 2018-04-28T05:38:25.143Z [Error configuring TLS: [error running "/opt/mqm/bin/runmqakm -cert -import": /opt/mqm/bin/runmqakm: exit status 24]]
abc_mq_1 exited with code 1
```

**Comment by parrobe** [comment]
Hi @stellirin,

We've identified a problem within the code that handles configuring TLS on MQ (specifically the keystore) that was preventing the container from starting. A fix is being developed and will be delivered soon. Once it has been delivered into this repo we will build it and push the fix to our 3 image stores (docker hub, docker store and IBM Cloud Container Registry) once it is there you will need to rebuild your image in order pick up these changes.  I will comment on this issue once the image is available.

One thing i did notice while testing your problem. In the `99-queues.mqsc` file you have added a line which changes the certificate label of the queue manager to `ibmq`. This will not work with the way we configure the queue manager when setting up TLS. Although your p12 keystore may have a certificate with the label `ibmq` in it when we convert that keystore to the one required by MQ the label is changed to `devcert`. Please remove this line from your mqsc file otherwise you will not be able to communicate with your queue manager through TLS.

**Comment by parrobe** [comment]
Fixed image is now available in docker store and docker hub and has been submitted to IBM Cloud Container registry for review.

Please rebuild your image from the docker store or docker hub versions and try again.

**Comment by stellirin** [comment]
Thanks @parrobe for the quick response, and for the tip about the certificate label. I was just about to start debugging why this stopped working. It was working when I was overwriting the {{10-dev.mqsc}} but at the last minute we decided to rename the file. I now see that the {{20-dev-tls.mqsc}} file was setting this correctly for us by overriding our label from {{ibmq}} back to {{devcert}}.

**Comment by stellirin** [comment]
@parrobe I was using the image from the Docker Store and so I was waiting for an updated image, but I just found that there are newer images on Docker Hub, so I tried that.

```
ibmcom/mq    9.0.5.0-x86_64    0e87ae1b5981    2 weeks ago    816MB
```
Unfortunately I still get the same results (exit status 24). I pushed a quick demo repo to https://github.com/stellirin/ibmq-tls (which better matches our current test setup) so you don't have to copy the files above and create test keys.
